/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdminLogin;

/**
 *
 * @author Sumanth
 */
public class UpdateSupplierJPanel extends javax.swing.JPanel {

    /**
     * Creates new form updateSupplierJPanel
     */
    public UpdateSupplierJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        activeBtn = new javax.swing.JRadioButton();
        disabledBtn = new javax.swing.JRadioButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Supplier Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 100, 30));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 110, 30));

        jLabel2.setText("Supplier UserName");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 100, 30));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 110, 30));

        jLabel3.setText("Supplier Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 100, 30));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 110, 30));

        jLabel4.setText("Confirm Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 100, 30));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 110, 30));

        jLabel5.setText("Account Status");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 160, 40));

        activeBtn.setText("Active");
        activeBtn.setEnabled(false);
        add(activeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        disabledBtn.setText("Disabled");
        disabledBtn.setEnabled(false);
        add(disabledBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activeBtn;
    private javax.swing.JRadioButton disabledBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
