/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdminLogin;

/**
 *
 * @author Sumanth
 */
public class UpdateSupplierJPanel extends javax.swing.JPanel {

    /**
     * Creates new form updateSupplierJPanel
     */
    public UpdateSupplierJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        activeBtn = new javax.swing.JRadioButton();
        disabledBtn = new javax.swing.JRadioButton();
        updateUserBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Supplier Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 100, 30));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 110, 30));

        jLabel2.setText("Supplier UserName");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 100, 30));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 110, 30));

        jLabel3.setText("Supplier Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 100, 30));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 110, 30));

        jLabel4.setText("Confirm Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 100, 30));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 110, 30));

        jLabel5.setText("Account Status");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 160, 40));

        activeBtn.setText("Active");
        activeBtn.setEnabled(false);
        add(activeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        disabledBtn.setText("Disabled");
        disabledBtn.setEnabled(false);
        add(disabledBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        updateUserBtn.setText("Update");
        updateUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserBtnActionPerformed(evt);
            }
        });
        add(updateUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 80, 30));

        saveBtn.setText("Save");
        saveBtn.setEnabled(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 70, 30));

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void updateUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserBtnActionPerformed
        activeBtn.setEnabled(true);
        disabledBtn.setEnabled(true);
        saveBtn.setEnabled(true);
        updateUserBtn.setEnabled(false);
    }//GEN-LAST:event_updateUserBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        activeBtn.setEnabled(false);
        disabledBtn.setEnabled(false);
        saveBtn.setEnabled(false);
        updateUserBtn.setEnabled(true);
        if(currentUser.getUserName().equals(person.getUser().getUserName())){
            activeBtn.setSelected(true);
            JOptionPane.showMessageDialog(null, "User cannot disable his own account");
            return;
        }
        if(activeBtn.isSelected()){
            person.getUser().setAccountStatus("Active");
        }else if(disabledBtn.isSelected()){
            person.getUser().setAccountStatus("Disabled");
        }
        JOptionPane.showMessageDialog(null, "User Account Updated Successfully");
    }//GEN-LAST:event_saveBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageSystemAdminJPanel panel = (ManageSystemAdminJPanel) component;
        panel.populateJTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activeBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JRadioButton disabledBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateUserBtn;
    // End of variables declaration//GEN-END:variables
}
