/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdminLogin.Revenue;

import Business.Business;
import Business.Order;
import Business.OrderList;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Sumanth
 */
public class TotalRevenueJPanel extends javax.swing.JPanel {

    /**
     * Creates new form totalRevenueJPanel
     */
    public TotalRevenueJPanel() {
        
        
    }
    
    JPanel userProcessContainer;
    Business business;
    public TotalRevenueJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business =business;
        ArrayList<OrderList> listOfOrders = business.getMasterOrderCatalog().getOrderList();
        double totalPrice=0;
        for(OrderList ol:listOfOrders){
            for(Order o:ol.getOrderList()){
                totalPrice = totalPrice+(o.getQuantity()*o.getSalesPrice());
            }
        }
        revenueTxt.setText(String.valueOf(totalPrice));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        revenueTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        revenueTxt.setEnabled(false);
        revenueTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenueTxtActionPerformed(evt);
            }
        });
        add(revenueTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 140, 40));

        jLabel3.setText("Total Revenue:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 100, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("                           Total Revenue");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 310, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void revenueTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenueTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_revenueTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField revenueTxt;
    // End of variables declaration//GEN-END:variables
}
